version: '3'
services:
  httpd:
    image: nginx:mainline-alpine
    depends_on:
      - app
    networks:
      - frontend
    ports:
      - "7070:80"
    volumes:
      - ./httpd/owncloud.conf:/etc/nginx/conf.d/default.conf
      - app:/srv/owncloud
    command: sh -c "chown -R nginx:nginx /srv/owncloud && chmod -R 777 /srv/owncloud && nginx -g 'daemon off;'"

  app:
    build: .
    depends_on:
      - objectstore
    networks:
      - roachnet
      - frontend
      - storage
    volumes:
      - app:/srv/owncloud

  objectstore:
    image: scality/s3server:latest
    build: objectstore
    restart: unless-stopped
    hostname: objectstore
    networks:
      - storage
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata

    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=verySecretKey1
      - SSL="FALSE"
      - LISTEN_ADDR=0.0.0.0

  db_node_1:
    image: cockroachdb/cockroach
    build: ./db
    command: start --insecure --listen-addr=db_node_1
    networks:
      - roachnet
    ports:
      - 8080:8080

  db_node_2:
    image: cockroachdb/cockroach
    command: start --insecure --join=db_node_1 --listen-addr=db_node_2
    networks:
      - roachnet

  db_node_3:
    image: cockroachdb/cockroach
    command: start --insecure --join=db_node_1 --listen-addr=db_node_3
    networks:
      - roachnet

  db_init:
    image: cockroachdb/cockroach
    networks:
      - roachnet
    volumes:
      - ./db/db_init.sh:/cockroach/db_init.sh
    depends_on:
      - db_node_1
      - db_node_2
      - db_node_3
    command: shell ./db_init.sh

volumes:
  app:
  s3data:
  s3metadata:
networks:
  roachnet:
  frontend:
  storage:







