version: '3'
services:
  httpd:
    image: nginx:mainline-alpine
    depends_on:
      - app
    links:
      - app
    ports:
      - "7070:80"
    volumes:
      - ./httpd/owncloud.conf:/etc/nginx/conf.d/default.conf
      - app:/srv/owncloud
    command: sh -c "chown -R nginx:nginx /srv/owncloud && nginx -g 'daemon off;'"

  app:
    build: .
    depends_on:
      - objectstore
    links:
      - objectstore
    volumes:
      - app:/srv/owncloud

  objectstore:
    image: scality/s3server:latest
    restart: unless-stopped
    ports:
      - "8000:8009"
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - SSL="FALSE"
volumes:
  app:
  s3data:
  s3metadata:







