version: '3'
services:
  owncloud:
    build: .
    links:
      - objectstore
    volumes:
      - owncloud_app:/srv/owncloud
  nginx:
    image: nginx:mainline-alpine
    links:
      - owncloud
    ports:
      - "7070:80"
    volumes:
      - ./owncloud.conf:/etc/nginx/conf.d/default.conf
      - owncloud_app:/srv/owncloud
    command: sh -c "chown -R nginx:nginx /srv/owncloud && nginx -g 'daemon off;'"

  objectstore:
    image: scality/s3server:latest
    restart: unless-stopped
    ports:
      - "8000:8009"
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - SSL="FALSE"

volumes:
  owncloud_app:
  s3data:
  s3metadata:







